services:
  app:
    build:
      context: ..
      dockerfile: docker/app/Dockerfile
    container_name: showcase_app
    restart: unless-stopped
    volumes:
      - ..:/var/www
    depends_on:
      - db
      - redis
    environment:
      - APP_ENV=local
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=showcase
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: >
      sh -c "chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache &&
             chmod -R 775 /var/www/storage /var/www/bootstrap/cache &&
             composer install --no-scripts --no-interaction &&
             php artisan config:clear &&
             php artisan cache:clear &&
             php-fpm"

  nginx:
    image: nginx:latest
    container_name: showcase_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ..:/var/www
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  vite:
    image: node:20
    container_name: showcase_vite
    working_dir: /var/www
    volumes:
      - ..:/var/www
    command: >
      sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "5189:5173"
    environment:
      - VITE_HOST=0.0.0.0
      - VITE_PORT=5173

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: showcase
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/default.cnf:/etc/mysql/conf.d/default.cnf

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "8096:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=root
    depends_on:
      - db

  redis:
    image: redis:7.0
    container_name: showcase_redis
    restart: unless-stopped
    ports:
      - "6385:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  mysql_data:
  redis_data: