services:
  app:
    build:
      context: ..
      dockerfile: docker/app/Dockerfile
    container_name: showcase_app
    restart: unless-stopped
    volumes:
      - ..:/var/www
    depends_on:
      - db
      - redis
    environment:
      - APP_ENV=local
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=showcase
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: >
      sh -c "chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache &&
             chmod -R 775 /var/www/storage /var/www/bootstrap/cache &&
             composer install --no-scripts --no-interaction &&
             php artisan config:clear &&
             php artisan cache:clear &&
             php-fpm"

  nginx:
    image: nginx:latest
    container_name: showcase_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ..:/var/www
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  vite:
    image: node:20
    container_name: showcase_vite
    working_dir: /var/www
    volumes:
      - ..:/var/www
    command: >
      sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "5173:5173"
    depends_on:
      - app

  db:
    image: postgres:15
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: showcase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: unless-stopped
    ports:
      - "9000:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=db
    depends_on:
      - db

  redis:
    image: redis:7.0
    container_name: showcase_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  postgres_data:
  redis_data: